### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by ben-barnard** [misken/obsimpy#7]
Would it be possible to upload them somewhere else? Really interested in your notebooks, I'm interested in clinical use of SimPy also.

**Comment by misken** [comment]
Fixed. I had migrated my old hselab blog to a new GitHub Pages site and have some old links here and there that I missed updating - thanks for letting me know. In addition to updating the two links, I added two additional links to more SimPy content I've created.

**Comment by ben-barnard** [comment]
Fantastic, thank you!
